name: build

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip android-ndk-r23b-linux.zip
    - name: Build injectprop
      run: |
        mkdir -p bin system/bin system/etc/init
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=aarch64-linux-android31-clang++ ./build.sh bin/injectprop_arm64
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=armv7a-linux-androideabi31-clang++ ./build.sh bin/injectprop_arm
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=i686-linux-android31-clang++ ./build.sh bin/injectprop_x86
        ANDROID_NDK_HOME=./android-ndk-r23b CXX=x86_64-linux-android31-clang++ ./build.sh bin/injectprop_x64
      
    - uses: actions/upload-artifact@v1
      with:
        name: injectprop
        path: |
            META-INF/*
            bin/*
            system/*
            addon.d/*
