name: release

on: [ workflow_dispatch ]

jobs:
   build: 
     uses: huskydg/injectprop/.github/workflows/build.yml@main
     with:
      branch: main

   release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
